export type CurrencyTemplate = {
  name: string;
  symbol: string;
  symbolNative: string;
  isoCode: string;
};

export const currencies: CurrencyTemplate[] = [
  {
    symbol: '$',
    name: 'US Dollar',
    symbolNative: '$',
    isoCode: 'USD',
  },
  {
    symbol: 'CA$',
    name: 'Canadian Dollar',
    symbolNative: '$',
    isoCode: 'CAD',
  },
  {
    symbol: '€',
    name: 'Euro',
    symbolNative: '€',
    isoCode: 'EUR',
  },
  {
    symbol: 'AED',
    name: 'United Arab Emirates Dirham',
    symbolNative: 'د.إ.',
    isoCode: 'AED',
  },
  {
    symbol: 'Af',
    name: 'Afghan Afghani',
    symbolNative: '؋',
    isoCode: 'AFN',
  },
  {
    symbol: 'ALL',
    name: 'Albanian Lek',
    symbolNative: 'Lek',
    isoCode: 'ALL',
  },
  {
    symbol: 'AMD',
    name: 'Armenian Dram',
    symbolNative: 'դր.',
    isoCode: 'AMD',
  },
  {
    symbol: 'AR$',
    name: 'Argentine Peso',
    symbolNative: '$',
    isoCode: 'ARS',
  },
  {
    symbol: 'AU$',
    name: 'Australian Dollar',
    symbolNative: '$',
    isoCode: 'AUD',
  },
  {
    symbol: 'man.',
    name: 'Azerbaijani Manat',
    symbolNative: 'ман.',
    isoCode: 'AZN',
  },
  {
    symbol: 'KM',
    name: 'Bosnia-Herzegovina Convertible Mark',
    symbolNative: 'KM',
    isoCode: 'BAM',
  },
  {
    symbol: 'Tk',
    name: 'Bangladeshi Taka',
    symbolNative: '৳',
    isoCode: 'BDT',
  },
  {
    symbol: 'BGN',
    name: 'Bulgarian Lev',
    symbolNative: 'лв.',
    isoCode: 'BGN',
  },
  {
    symbol: 'BD',
    name: 'Bahraini Dinar',
    symbolNative: 'د.ب.',
    isoCode: 'BHD',
  },
  {
    symbol: 'FBu',
    name: 'Burundian Franc',
    symbolNative: 'FBu',
    isoCode: 'BIF',
  },
  {
    symbol: 'BN$',
    name: 'Brunei Dollar',
    symbolNative: '$',
    isoCode: 'BND',
  },
  {
    symbol: 'Bs',
    name: 'Bolivian Boliviano',
    symbolNative: 'Bs',
    isoCode: 'BOB',
  },
  {
    symbol: 'R$',
    name: 'Brazilian Real',
    symbolNative: 'R$',
    isoCode: 'BRL',
  },
  {
    symbol: 'BWP',
    name: 'Botswanan Pula',
    symbolNative: 'P',
    isoCode: 'BWP',
  },
  {
    symbol: 'BYR',
    name: 'Belarusian Ruble',
    symbolNative: 'BYR',
    isoCode: 'BYR',
  },
  {
    symbol: 'BZ$',
    name: 'Belize Dollar',
    symbolNative: '$',
    isoCode: 'BZD',
  },
  {
    symbol: 'CDF',
    name: 'Congolese Franc',
    symbolNative: 'FrCD',
    isoCode: 'CDF',
  },
  {
    symbol: 'CHF',
    name: 'Swiss Franc',
    symbolNative: 'CHF',
    isoCode: 'CHF',
  },
  {
    symbol: 'CL$',
    name: 'Chilean Peso',
    symbolNative: '$',
    isoCode: 'CLP',
  },
  {
    symbol: 'CN¥',
    name: 'Chinese Yuan',
    symbolNative: 'CN¥',
    isoCode: 'CNY',
  },
  {
    symbol: 'CO$',
    name: 'Colombian Peso',
    symbolNative: '$',
    isoCode: 'COP',
  },
  {
    symbol: '₡',
    name: 'Costa Rican Colón',
    symbolNative: '₡',
    isoCode: 'CRC',
  },
  {
    symbol: 'CV$',
    name: 'Cape Verdean Escudo',
    symbolNative: 'CV$',
    isoCode: 'CVE',
  },
  {
    symbol: 'Kč',
    name: 'Czech Republic Koruna',
    symbolNative: 'Kč',
    isoCode: 'CZK',
  },
  {
    symbol: 'Fdj',
    name: 'Djiboutian Franc',
    symbolNative: 'Fdj',
    isoCode: 'DJF',
  },
  {
    symbol: 'Dkr',
    name: 'Danish Krone',
    symbolNative: 'kr',
    isoCode: 'DKK',
  },
  {
    symbol: 'RD$',
    name: 'Dominican Peso',
    symbolNative: 'RD$',
    isoCode: 'DOP',
  },
  {
    symbol: 'DA',
    name: 'Algerian Dinar',
    symbolNative: 'د.ج.',
    isoCode: 'DZD',
  },
  {
    symbol: 'Ekr',
    name: 'Estonian Kroon',
    symbolNative: 'kr',
    isoCode: 'EEK',
  },
  {
    symbol: 'EGP',
    name: 'Egyptian Pound',
    symbolNative: 'ج.م.',
    isoCode: 'EGP',
  },
  {
    symbol: 'Nfk',
    name: 'Eritrean Nakfa',
    symbolNative: 'Nfk',
    isoCode: 'ERN',
  },
  {
    symbol: 'Br',
    name: 'Ethiopian Birr',
    symbolNative: 'Br',
    isoCode: 'ETB',
  },
  {
    symbol: '£',
    name: 'British Pound Sterling',
    symbolNative: '£',
    isoCode: 'GBP',
  },
  {
    symbol: 'GEL',
    name: 'Georgian Lari',
    symbolNative: 'GEL',
    isoCode: 'GEL',
  },
  {
    symbol: 'GH₵',
    name: 'Ghanaian Cedi',
    symbolNative: 'GH₵',
    isoCode: 'GHS',
  },
  {
    symbol: 'FG',
    name: 'Guinean Franc',
    symbolNative: 'FG',
    isoCode: 'GNF',
  },
  {
    symbol: 'GTQ',
    name: 'Guatemalan Quetzal',
    symbolNative: 'Q',
    isoCode: 'GTQ',
  },
  {
    symbol: 'HK$',
    name: 'Hong Kong Dollar',
    symbolNative: '$',
    isoCode: 'HKD',
  },
  {
    symbol: 'HNL',
    name: 'Honduran Lempira',
    symbolNative: 'L',
    isoCode: 'HNL',
  },
  {
    symbol: 'kn',
    name: 'Croatian Kuna',
    symbolNative: 'kn',
    isoCode: 'HRK',
  },
  {
    symbol: 'Ft',
    name: 'Hungarian Forint',
    symbolNative: 'Ft',
    isoCode: 'HUF',
  },
  {
    symbol: 'Rp',
    name: 'Indonesian Rupiah',
    symbolNative: 'Rp',
    isoCode: 'IDR',
  },
  {
    symbol: '₪',
    name: 'Israeli New Sheqel',
    symbolNative: '₪',
    isoCode: 'ILS',
  },
  {
    symbol: 'Rs',
    name: 'Indian Rupee',
    symbolNative: 'টকা',
    isoCode: 'INR',
  },
  {
    symbol: 'IQD',
    name: 'Iraqi Dinar',
    symbolNative: 'د.ع.',
    isoCode: 'IQD',
  },
  {
    symbol: 'IRR',
    name: 'Iranian Rial',
    symbolNative: '﷼',
    isoCode: 'IRR',
  },
  {
    symbol: 'Ikr',
    name: 'Icelandic Króna',
    symbolNative: 'kr',
    isoCode: 'ISK',
  },
  {
    symbol: 'J$',
    name: 'Jamaican Dollar',
    symbolNative: '$',
    isoCode: 'JMD',
  },
  {
    symbol: 'JD',
    name: 'Jordanian Dinar',
    symbolNative: 'د.أ.',
    isoCode: 'JOD',
  },
  {
    symbol: '¥',
    name: 'Japanese Yen',
    symbolNative: '￥',
    isoCode: 'JPY',
  },
  {
    symbol: 'Ksh',
    name: 'Kenyan Shilling',
    symbolNative: 'Ksh',
    isoCode: 'KES',
  },
  {
    symbol: 'KHR',
    name: 'Cambodian Riel',
    symbolNative: '៛',
    isoCode: 'KHR',
  },
  {
    symbol: 'CF',
    name: 'Comorian Franc',
    symbolNative: 'FC',
    isoCode: 'KMF',
  },
  {
    symbol: '₩',
    name: 'South Korean Won',
    symbolNative: '₩',
    isoCode: 'KRW',
  },
  {
    symbol: 'KD',
    name: 'Kuwaiti Dinar',
    symbolNative: 'د.ك.',
    isoCode: 'KWD',
  },
  {
    symbol: 'KZT',
    name: 'Kazakhstani Tenge',
    symbolNative: 'тңг.',
    isoCode: 'KZT',
  },
  {
    symbol: 'LB£',
    name: 'Lebanese Pound',
    symbolNative: 'ل.ل.',
    isoCode: 'LBP',
  },
  {
    symbol: 'SLRs',
    name: 'Sri Lankan Rupee',
    symbolNative: 'SL Re',
    isoCode: 'LKR',
  },
  {
    symbol: 'Lt',
    name: 'Lithuanian Litas',
    symbolNative: 'Lt',
    isoCode: 'LTL',
  },
  {
    symbol: 'Ls',
    name: 'Latvian Lats',
    symbolNative: 'Ls',
    isoCode: 'LVL',
  },
  {
    symbol: 'LD',
    name: 'Libyan Dinar',
    symbolNative: 'د.ل.',
    isoCode: 'LYD',
  },
  {
    symbol: 'MAD',
    name: 'Moroccan Dirham',
    symbolNative: 'د.م.',
    isoCode: 'MAD',
  },
  {
    symbol: 'MDL',
    name: 'Moldovan Leu',
    symbolNative: 'MDL',
    isoCode: 'MDL',
  },
  {
    symbol: 'MGA',
    name: 'Malagasy Ariary',
    symbolNative: 'MGA',
    isoCode: 'MGA',
  },
  {
    symbol: 'MKD',
    name: 'Macedonian Denar',
    symbolNative: 'MKD',
    isoCode: 'MKD',
  },
  {
    symbol: 'MMK',
    name: 'Myanma Kyat',
    symbolNative: 'K',
    isoCode: 'MMK',
  },
  {
    symbol: 'MOP$',
    name: 'Macanese Pataca',
    symbolNative: 'MOP$',
    isoCode: 'MOP',
  },
  {
    symbol: 'MURs',
    name: 'Mauritian Rupee',
    symbolNative: 'MURs',
    isoCode: 'MUR',
  },
  {
    symbol: 'MX$',
    name: 'Mexican Peso',
    symbolNative: '$',
    isoCode: 'MXN',
  },
  {
    symbol: 'RM',
    name: 'Malaysian Ringgit',
    symbolNative: 'RM',
    isoCode: 'MYR',
  },
  {
    symbol: 'MTn',
    name: 'Mozambican Metical',
    symbolNative: 'MTn',
    isoCode: 'MZN',
  },
  {
    symbol: 'N$',
    name: 'Namibian Dollar',
    symbolNative: 'N$',
    isoCode: 'NAD',
  },
  {
    symbol: '₦',
    name: 'Nigerian Naira',
    symbolNative: '₦',
    isoCode: 'NGN',
  },
  {
    symbol: 'C$',
    name: 'Nicaraguan Córdoba',
    symbolNative: 'C$',
    isoCode: 'NIO',
  },
  {
    symbol: 'Nkr',
    name: 'Norwegian Krone',
    symbolNative: 'kr',
    isoCode: 'NOK',
  },
  {
    symbol: 'NPRs',
    name: 'Nepalese Rupee',
    symbolNative: 'नेरू',
    isoCode: 'NPR',
  },
  {
    symbol: 'NZ$',
    name: 'New Zealand Dollar',
    symbolNative: '$',
    isoCode: 'NZD',
  },
  {
    symbol: 'OMR',
    name: 'Omani Rial',
    symbolNative: 'ر.ع.',
    isoCode: 'OMR',
  },
  {
    symbol: 'B/.',
    name: 'Panamanian Balboa',
    symbolNative: 'B/.',
    isoCode: 'PAB',
  },
  {
    symbol: 'S/.',
    name: 'Peruvian Nuevo Sol',
    symbolNative: 'S/.',
    isoCode: 'PEN',
  },
  {
    symbol: '₱',
    name: 'Philippine Peso',
    symbolNative: '₱',
    isoCode: 'PHP',
  },
  {
    symbol: 'PKRs',
    name: 'Pakistani Rupee',
    symbolNative: '₨',
    isoCode: 'PKR',
  },
  {
    symbol: 'zł',
    name: 'Polish Zloty',
    symbolNative: 'zł',
    isoCode: 'PLN',
  },
  {
    symbol: '₲',
    name: 'Paraguayan Guarani',
    symbolNative: '₲',
    isoCode: 'PYG',
  },
  {
    symbol: 'QR',
    name: 'Qatari Rial',
    symbolNative: 'ر.ق.',
    isoCode: 'QAR',
  },
  {
    symbol: 'RON',
    name: 'Romanian Leu',
    symbolNative: 'RON',
    isoCode: 'RON',
  },
  {
    symbol: 'din.',
    name: 'Serbian Dinar',
    symbolNative: 'дин.',
    isoCode: 'RSD',
  },
  {
    symbol: 'RUB',
    name: 'Russian Ruble',
    symbolNative: 'руб.',
    isoCode: 'RUB',
  },
  {
    symbol: 'RWF',
    name: 'Rwandan Franc',
    symbolNative: 'FR',
    isoCode: 'RWF',
  },
  {
    symbol: 'SR',
    name: 'Saudi Riyal',
    symbolNative: 'ر.س.',
    isoCode: 'SAR',
  },
  {
    symbol: 'SDG',
    name: 'Sudanese Pound',
    symbolNative: 'SDG',
    isoCode: 'SDG',
  },
  {
    symbol: 'Skr',
    name: 'Swedish Krona',
    symbolNative: 'kr',
    isoCode: 'SEK',
  },
  {
    symbol: 'S$',
    name: 'Singapore Dollar',
    symbolNative: '$',
    isoCode: 'SGD',
  },
  {
    symbol: 'Ssh',
    name: 'Somali Shilling',
    symbolNative: 'Ssh',
    isoCode: 'SOS',
  },
  {
    symbol: 'SY£',
    name: 'Syrian Pound',
    symbolNative: 'ل.س.',
    isoCode: 'SYP',
  },
  {
    symbol: '฿',
    name: 'Thai Baht',
    symbolNative: '฿',
    isoCode: 'THB',
  },
  {
    symbol: 'DT',
    name: 'Tunisian Dinar',
    symbolNative: 'د.ت.',
    isoCode: 'TND',
  },
  {
    symbol: 'T$',
    name: 'Tongan Paʻanga',
    symbolNative: 'T$',
    isoCode: 'TOP',
  },
  {
    symbol: 'TL',
    name: 'Turkish Lira',
    symbolNative: 'TL',
    isoCode: 'TRY',
  },
  {
    symbol: 'TT$',
    name: 'Trinidad and Tobago Dollar',
    symbolNative: '$',
    isoCode: 'TTD',
  },
  {
    symbol: 'NT$',
    name: 'New Taiwan Dollar',
    symbolNative: 'NT$',
    isoCode: 'TWD',
  },
  {
    symbol: 'TSh',
    name: 'Tanzanian Shilling',
    symbolNative: 'TSh',
    isoCode: 'TZS',
  },
  {
    symbol: '₴',
    name: 'Ukrainian Hryvnia',
    symbolNative: '₴',
    isoCode: 'UAH',
  },
  {
    symbol: 'USh',
    name: 'Ugandan Shilling',
    symbolNative: 'USh',
    isoCode: 'UGX',
  },
  {
    symbol: '$U',
    name: 'Uruguayan Peso',
    symbolNative: '$',
    isoCode: 'UYU',
  },
  {
    symbol: 'UZS',
    name: 'Uzbekistan Som',
    symbolNative: 'UZS',
    isoCode: 'UZS',
  },
  {
    symbol: 'Bs.F.',
    name: 'Venezuelan Bolívar',
    symbolNative: 'Bs.F.',
    isoCode: 'VEF',
  },
  {
    symbol: '₫',
    name: 'Vietnamese Dong',
    symbolNative: '₫',
    isoCode: 'VND',
  },
  {
    symbol: 'FCFA',
    name: 'CFA Franc BEAC',
    symbolNative: 'FCFA',
    isoCode: 'XAF',
  },
  {
    symbol: 'CFA',
    name: 'CFA Franc BCEAO',
    symbolNative: 'CFA',
    isoCode: 'XOF',
  },
  {
    symbol: 'YR',
    name: 'Yemeni Rial',
    symbolNative: 'ر.ي.',
    isoCode: 'YER',
  },
  {
    symbol: 'R',
    name: 'South African Rand',
    symbolNative: 'R',
    isoCode: 'ZAR',
  },
  {
    symbol: 'ZK',
    name: 'Zambian Kwacha',
    symbolNative: 'ZK',
    isoCode: 'ZMK',
  },
];
